services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: GinTalk
      MYSQL_USER: docker
      MYSQL_PASSWORD: 123456
    command: --innodb-buffer-pool-size=2G
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  mysql_data:
  redis_data:
