// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommentRelation = "comment_relation"

// CommentRelation 评论关系表：存储评论的层级关系
type CommentRelation struct {
	PostID     int64     `gorm:"column:post_id;not null;comment:评论所属的帖子ID" json:"post_id"`                                   // 评论所属的帖子ID
	CommentID  int64     `gorm:"column:comment_id;primaryKey;comment:评论ID, 用于关联评论表" json:"comment_id"`                       // 评论ID, 用于关联评论表
	ParentID   int64     `gorm:"column:parent_id;not null;comment:父评论ID, 0表示一级评论, 其他值表示回复的评论ID" json:"parent_id"`            // 父评论ID, 0表示一级评论, 其他值表示回复的评论ID
	ReplyID    int64     `gorm:"column:reply_id;not null;comment:回复的评论的comment_id" json:"reply_id"`                          // 回复的评论的comment_id
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:评论关系创建时间，默认当前时间" json:"create_time"`    // 评论关系创建时间，默认当前时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:评论关系更新时间，每次更新时自动修改" json:"update_time"` // 评论关系更新时间，每次更新时自动修改
	DeleteTime int       `gorm:"column:delete_time;comment:逻辑删除时间，NULL表示未删除" json:"delete_time"`                             // 逻辑删除时间，NULL表示未删除
}

// TableName CommentRelation's table name
func (*CommentRelation) TableName() string {
	return TableNameCommentRelation
}
