// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePost = "post"

// Post 帖子表：存储用户发布的帖子及其状态
type Post struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键，唯一标识每条帖子记录" json:"id"`                // 自增主键，唯一标识每条帖子记录
	PostID      int64     `gorm:"column:post_id;not null;comment:帖子ID，用于业务中的帖子唯一标识" json:"post_id"`                         // 帖子ID，用于业务中的帖子唯一标识
	Title       string    `gorm:"column:title;not null;comment:帖子标题" json:"title"`                                          // 帖子标题
	Summary     string    `gorm:"column:summary;not null;comment:帖子摘要" json:"summary"`                                      // 帖子摘要
	AuthorID    int64     `gorm:"column:author_id;not null;comment:作者的用户ID，用于关联用户表" json:"author_id"`                       // 作者的用户ID，用于关联用户表
	CommunityID int64     `gorm:"column:community_id;not null;comment:所属社区ID，用于关联社区表" json:"community_id"`                  // 所属社区ID，用于关联社区表
	Status      int32     `gorm:"column:status;not null;default:1;comment:帖子状态：1-正常，0-隐藏或删除" json:"status"`                 // 帖子状态：1-正常，0-隐藏或删除
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:帖子创建时间，默认当前时间" json:"create_time"`    // 帖子创建时间，默认当前时间
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:帖子更新时间，每次更新时自动修改" json:"update_time"` // 帖子更新时间，每次更新时自动修改
	DeleteTime  int       `gorm:"column:delete_time;comment:逻辑删除时间，NULL表示未删除" json:"delete_time"`                           // 逻辑删除时间，NULL表示未删除
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
