// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePostContent = "post_content"

// PostContent 帖子内容表：存储帖子的详细内容
type PostContent struct {
	PostID     int64     `gorm:"column:post_id;primaryKey;comment:帖子ID" json:"post_id"`                                      // 帖子ID
	Content    string    `gorm:"column:content;not null;comment:帖子内容" json:"content"`                                        // 帖子内容
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:帖子内容创建时间，默认当前时间" json:"create_time"`    // 帖子内容创建时间，默认当前时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:帖子内容更新时间，每次更新时自动修改" json:"update_time"` // 帖子内容更新时间，每次更新时自动修改
	DeleteTime int       `gorm:"column:delete_time;comment:逻辑删除时间，NULL表示未删除" json:"delete_time"`                             // 逻辑删除时间，NULL表示未删除
}

// TableName PostContent's table name
func (*PostContent) TableName() string {
	return TableNamePostContent
}
